# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputText', models.CharField(max_length=5000)),
                ('detectedLanguage', models.CharField(max_length=25)),
                ('translatedText', models.CharField(max_length=5000)),
            ],
        ),
    ]
